#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemirbasTakip
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DemirbasTakip")]
	public partial class DemirbasDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_Calisanlar(tbl_Calisanlar instance);
    partial void Updatetbl_Calisanlar(tbl_Calisanlar instance);
    partial void Deletetbl_Calisanlar(tbl_Calisanlar instance);
    partial void Inserttbl_Kullanicilar(tbl_Kullanicilar instance);
    partial void Updatetbl_Kullanicilar(tbl_Kullanicilar instance);
    partial void Deletetbl_Kullanicilar(tbl_Kullanicilar instance);
    partial void Inserttbl_Urunler(tbl_Urunler instance);
    partial void Updatetbl_Urunler(tbl_Urunler instance);
    partial void Deletetbl_Urunler(tbl_Urunler instance);
    partial void Inserttbl_Zimmetliler(tbl_Zimmetliler instance);
    partial void Updatetbl_Zimmetliler(tbl_Zimmetliler instance);
    partial void Deletetbl_Zimmetliler(tbl_Zimmetliler instance);
    partial void Inserttbl_Servisler(tbl_Servisler instance);
    partial void Updatetbl_Servisler(tbl_Servisler instance);
    partial void Deletetbl_Servisler(tbl_Servisler instance);
    partial void Inserttbl_UrunKategori(tbl_UrunKategori instance);
    partial void Updatetbl_UrunKategori(tbl_UrunKategori instance);
    partial void Deletetbl_UrunKategori(tbl_UrunKategori instance);
    partial void Inserttbl_AltUrunKategori(tbl_AltUrunKategori instance);
    partial void Updatetbl_AltUrunKategori(tbl_AltUrunKategori instance);
    partial void Deletetbl_AltUrunKategori(tbl_AltUrunKategori instance);
    #endregion
		
		public DemirbasDBDataContext() : 
				base(global::DemirbasTakip.Properties.Settings.Default.DemirbasTakipConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DemirbasDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemirbasDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemirbasDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemirbasDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Calisanlar> tbl_Calisanlars
		{
			get
			{
				return this.GetTable<tbl_Calisanlar>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Kullanicilar> tbl_Kullanicilars
		{
			get
			{
				return this.GetTable<tbl_Kullanicilar>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Urunler> tbl_Urunlers
		{
			get
			{
				return this.GetTable<tbl_Urunler>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Zimmetliler> tbl_Zimmetlilers
		{
			get
			{
				return this.GetTable<tbl_Zimmetliler>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Servisler> tbl_Servislers
		{
			get
			{
				return this.GetTable<tbl_Servisler>();
			}
		}
		
		public System.Data.Linq.Table<tbl_UrunKategori> tbl_UrunKategoris
		{
			get
			{
				return this.GetTable<tbl_UrunKategori>();
			}
		}
		
		public System.Data.Linq.Table<tbl_AltUrunKategori> tbl_AltUrunKategoris
		{
			get
			{
				return this.GetTable<tbl_AltUrunKategori>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Calisanlar")]
	public partial class tbl_Calisanlar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cid;
		
		private string _cAdSoyad;
		
		private System.DateTime _cGirTah;
		
		private string _cTur;
		
		private bool _cSilindi;
		
		private EntitySet<tbl_Zimmetliler> _tbl_Zimmetlilers;
		
		private EntitySet<tbl_Servisler> _tbl_Servislers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncidChanging(int value);
    partial void OncidChanged();
    partial void OncAdSoyadChanging(string value);
    partial void OncAdSoyadChanged();
    partial void OncGirTahChanging(System.DateTime value);
    partial void OncGirTahChanged();
    partial void OncTurChanging(string value);
    partial void OncTurChanged();
    partial void OncSilindiChanging(bool value);
    partial void OncSilindiChanged();
    #endregion
		
		public tbl_Calisanlar()
		{
			this._tbl_Zimmetlilers = new EntitySet<tbl_Zimmetliler>(new Action<tbl_Zimmetliler>(this.attach_tbl_Zimmetlilers), new Action<tbl_Zimmetliler>(this.detach_tbl_Zimmetlilers));
			this._tbl_Servislers = new EntitySet<tbl_Servisler>(new Action<tbl_Servisler>(this.attach_tbl_Servislers), new Action<tbl_Servisler>(this.detach_tbl_Servislers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cid
		{
			get
			{
				return this._cid;
			}
			set
			{
				if ((this._cid != value))
				{
					this.OncidChanging(value);
					this.SendPropertyChanging();
					this._cid = value;
					this.SendPropertyChanged("cid");
					this.OncidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cAdSoyad", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string cAdSoyad
		{
			get
			{
				return this._cAdSoyad;
			}
			set
			{
				if ((this._cAdSoyad != value))
				{
					this.OncAdSoyadChanging(value);
					this.SendPropertyChanging();
					this._cAdSoyad = value;
					this.SendPropertyChanged("cAdSoyad");
					this.OncAdSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cGirTah", DbType="DateTime NOT NULL")]
		public System.DateTime cGirTah
		{
			get
			{
				return this._cGirTah;
			}
			set
			{
				if ((this._cGirTah != value))
				{
					this.OncGirTahChanging(value);
					this.SendPropertyChanging();
					this._cGirTah = value;
					this.SendPropertyChanged("cGirTah");
					this.OncGirTahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cTur", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string cTur
		{
			get
			{
				return this._cTur;
			}
			set
			{
				if ((this._cTur != value))
				{
					this.OncTurChanging(value);
					this.SendPropertyChanging();
					this._cTur = value;
					this.SendPropertyChanged("cTur");
					this.OncTurChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cSilindi", DbType="Bit NOT NULL")]
		public bool cSilindi
		{
			get
			{
				return this._cSilindi;
			}
			set
			{
				if ((this._cSilindi != value))
				{
					this.OncSilindiChanging(value);
					this.SendPropertyChanging();
					this._cSilindi = value;
					this.SendPropertyChanged("cSilindi");
					this.OncSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Calisanlar_tbl_Zimmetliler", Storage="_tbl_Zimmetlilers", ThisKey="cid", OtherKey="Calisanid")]
		public EntitySet<tbl_Zimmetliler> tbl_Zimmetlilers
		{
			get
			{
				return this._tbl_Zimmetlilers;
			}
			set
			{
				this._tbl_Zimmetlilers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Calisanlar_tbl_Servisler", Storage="_tbl_Servislers", ThisKey="cid", OtherKey="calisanid")]
		public EntitySet<tbl_Servisler> tbl_Servislers
		{
			get
			{
				return this._tbl_Servislers;
			}
			set
			{
				this._tbl_Servislers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Zimmetlilers(tbl_Zimmetliler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Calisanlar = this;
		}
		
		private void detach_tbl_Zimmetlilers(tbl_Zimmetliler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Calisanlar = null;
		}
		
		private void attach_tbl_Servislers(tbl_Servisler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Calisanlar = this;
		}
		
		private void detach_tbl_Servislers(tbl_Servisler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Calisanlar = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Kullanicilar")]
	public partial class tbl_Kullanicilar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kid;
		
		private string _kTc;
		
		private string _kSifre;
		
		private bool _kSilindi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkidChanging(int value);
    partial void OnkidChanged();
    partial void OnkTcChanging(string value);
    partial void OnkTcChanged();
    partial void OnkSifreChanging(string value);
    partial void OnkSifreChanged();
    partial void OnkSilindiChanging(bool value);
    partial void OnkSilindiChanged();
    #endregion
		
		public tbl_Kullanicilar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kid
		{
			get
			{
				return this._kid;
			}
			set
			{
				if ((this._kid != value))
				{
					this.OnkidChanging(value);
					this.SendPropertyChanging();
					this._kid = value;
					this.SendPropertyChanged("kid");
					this.OnkidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kTc", DbType="Char(11) NOT NULL", CanBeNull=false)]
		public string kTc
		{
			get
			{
				return this._kTc;
			}
			set
			{
				if ((this._kTc != value))
				{
					this.OnkTcChanging(value);
					this.SendPropertyChanging();
					this._kTc = value;
					this.SendPropertyChanged("kTc");
					this.OnkTcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kSifre", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string kSifre
		{
			get
			{
				return this._kSifre;
			}
			set
			{
				if ((this._kSifre != value))
				{
					this.OnkSifreChanging(value);
					this.SendPropertyChanging();
					this._kSifre = value;
					this.SendPropertyChanged("kSifre");
					this.OnkSifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kSilindi", DbType="Bit NOT NULL")]
		public bool kSilindi
		{
			get
			{
				return this._kSilindi;
			}
			set
			{
				if ((this._kSilindi != value))
				{
					this.OnkSilindiChanging(value);
					this.SendPropertyChanging();
					this._kSilindi = value;
					this.SendPropertyChanged("kSilindi");
					this.OnkSilindiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Urunler")]
	public partial class tbl_Urunler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _barkod;
		
		private string _Ad;
		
		private int _Kategoriid;
		
		private System.DateTime _GirisTah;
		
		private System.DateTime _GarantiBas;
		
		private System.DateTime _GarantiSon;
		
		private int _AltKategoriid;
		
		private bool _Silindi;
		
		private EntitySet<tbl_Zimmetliler> _tbl_Zimmetlilers;
		
		private EntitySet<tbl_Servisler> _tbl_Servislers;
		
		private EntityRef<tbl_UrunKategori> _tbl_UrunKategori;
		
		private EntityRef<tbl_AltUrunKategori> _tbl_AltUrunKategori;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnbarkodChanging(int value);
    partial void OnbarkodChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnKategoriidChanging(int value);
    partial void OnKategoriidChanged();
    partial void OnGirisTahChanging(System.DateTime value);
    partial void OnGirisTahChanged();
    partial void OnGarantiBasChanging(System.DateTime value);
    partial void OnGarantiBasChanged();
    partial void OnGarantiSonChanging(System.DateTime value);
    partial void OnGarantiSonChanged();
    partial void OnAltKategoriidChanging(int value);
    partial void OnAltKategoriidChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    #endregion
		
		public tbl_Urunler()
		{
			this._tbl_Zimmetlilers = new EntitySet<tbl_Zimmetliler>(new Action<tbl_Zimmetliler>(this.attach_tbl_Zimmetlilers), new Action<tbl_Zimmetliler>(this.detach_tbl_Zimmetlilers));
			this._tbl_Servislers = new EntitySet<tbl_Servisler>(new Action<tbl_Servisler>(this.attach_tbl_Servislers), new Action<tbl_Servisler>(this.detach_tbl_Servislers));
			this._tbl_UrunKategori = default(EntityRef<tbl_UrunKategori>);
			this._tbl_AltUrunKategori = default(EntityRef<tbl_AltUrunKategori>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barkod", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int barkod
		{
			get
			{
				return this._barkod;
			}
			set
			{
				if ((this._barkod != value))
				{
					this.OnbarkodChanging(value);
					this.SendPropertyChanging();
					this._barkod = value;
					this.SendPropertyChanged("barkod");
					this.OnbarkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kategoriid", DbType="Int NOT NULL")]
		public int Kategoriid
		{
			get
			{
				return this._Kategoriid;
			}
			set
			{
				if ((this._Kategoriid != value))
				{
					if (this._tbl_UrunKategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKategoriidChanging(value);
					this.SendPropertyChanging();
					this._Kategoriid = value;
					this.SendPropertyChanged("Kategoriid");
					this.OnKategoriidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GirisTah", DbType="DateTime NOT NULL")]
		public System.DateTime GirisTah
		{
			get
			{
				return this._GirisTah;
			}
			set
			{
				if ((this._GirisTah != value))
				{
					this.OnGirisTahChanging(value);
					this.SendPropertyChanging();
					this._GirisTah = value;
					this.SendPropertyChanged("GirisTah");
					this.OnGirisTahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GarantiBas", DbType="DateTime NOT NULL")]
		public System.DateTime GarantiBas
		{
			get
			{
				return this._GarantiBas;
			}
			set
			{
				if ((this._GarantiBas != value))
				{
					this.OnGarantiBasChanging(value);
					this.SendPropertyChanging();
					this._GarantiBas = value;
					this.SendPropertyChanged("GarantiBas");
					this.OnGarantiBasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GarantiSon", DbType="DateTime NOT NULL")]
		public System.DateTime GarantiSon
		{
			get
			{
				return this._GarantiSon;
			}
			set
			{
				if ((this._GarantiSon != value))
				{
					this.OnGarantiSonChanging(value);
					this.SendPropertyChanging();
					this._GarantiSon = value;
					this.SendPropertyChanged("GarantiSon");
					this.OnGarantiSonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AltKategoriid", DbType="Int NOT NULL")]
		public int AltKategoriid
		{
			get
			{
				return this._AltKategoriid;
			}
			set
			{
				if ((this._AltKategoriid != value))
				{
					if (this._tbl_AltUrunKategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAltKategoriidChanging(value);
					this.SendPropertyChanging();
					this._AltKategoriid = value;
					this.SendPropertyChanged("AltKategoriid");
					this.OnAltKategoriidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Urunler_tbl_Zimmetliler", Storage="_tbl_Zimmetlilers", ThisKey="barkod", OtherKey="Barkod")]
		public EntitySet<tbl_Zimmetliler> tbl_Zimmetlilers
		{
			get
			{
				return this._tbl_Zimmetlilers;
			}
			set
			{
				this._tbl_Zimmetlilers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Urunler_tbl_Servisler", Storage="_tbl_Servislers", ThisKey="barkod", OtherKey="Barkod")]
		public EntitySet<tbl_Servisler> tbl_Servislers
		{
			get
			{
				return this._tbl_Servislers;
			}
			set
			{
				this._tbl_Servislers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_UrunKategori_tbl_Urunler", Storage="_tbl_UrunKategori", ThisKey="Kategoriid", OtherKey="id", IsForeignKey=true)]
		public tbl_UrunKategori tbl_UrunKategori
		{
			get
			{
				return this._tbl_UrunKategori.Entity;
			}
			set
			{
				tbl_UrunKategori previousValue = this._tbl_UrunKategori.Entity;
				if (((previousValue != value) 
							|| (this._tbl_UrunKategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_UrunKategori.Entity = null;
						previousValue.tbl_Urunlers.Remove(this);
					}
					this._tbl_UrunKategori.Entity = value;
					if ((value != null))
					{
						value.tbl_Urunlers.Add(this);
						this._Kategoriid = value.id;
					}
					else
					{
						this._Kategoriid = default(int);
					}
					this.SendPropertyChanged("tbl_UrunKategori");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_AltUrunKategori_tbl_Urunler", Storage="_tbl_AltUrunKategori", ThisKey="AltKategoriid", OtherKey="id", IsForeignKey=true)]
		public tbl_AltUrunKategori tbl_AltUrunKategori
		{
			get
			{
				return this._tbl_AltUrunKategori.Entity;
			}
			set
			{
				tbl_AltUrunKategori previousValue = this._tbl_AltUrunKategori.Entity;
				if (((previousValue != value) 
							|| (this._tbl_AltUrunKategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_AltUrunKategori.Entity = null;
						previousValue.tbl_Urunlers.Remove(this);
					}
					this._tbl_AltUrunKategori.Entity = value;
					if ((value != null))
					{
						value.tbl_Urunlers.Add(this);
						this._AltKategoriid = value.id;
					}
					else
					{
						this._AltKategoriid = default(int);
					}
					this.SendPropertyChanged("tbl_AltUrunKategori");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Zimmetlilers(tbl_Zimmetliler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Urunler = this;
		}
		
		private void detach_tbl_Zimmetlilers(tbl_Zimmetliler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Urunler = null;
		}
		
		private void attach_tbl_Servislers(tbl_Servisler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Urunler = this;
		}
		
		private void detach_tbl_Servislers(tbl_Servisler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Urunler = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Zimmetliler")]
	public partial class tbl_Zimmetliler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Barkod;
		
		private int _Calisanid;
		
		private System.DateTime _Baslangic;
		
		private System.Nullable<System.DateTime> _Bitis;
		
		private bool _Silindi;
		
		private EntityRef<tbl_Calisanlar> _tbl_Calisanlar;
		
		private EntityRef<tbl_Urunler> _tbl_Urunler;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnBarkodChanging(int value);
    partial void OnBarkodChanged();
    partial void OnCalisanidChanging(int value);
    partial void OnCalisanidChanged();
    partial void OnBaslangicChanging(System.DateTime value);
    partial void OnBaslangicChanged();
    partial void OnBitisChanging(System.Nullable<System.DateTime> value);
    partial void OnBitisChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    #endregion
		
		public tbl_Zimmetliler()
		{
			this._tbl_Calisanlar = default(EntityRef<tbl_Calisanlar>);
			this._tbl_Urunler = default(EntityRef<tbl_Urunler>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barkod", DbType="Int NOT NULL")]
		public int Barkod
		{
			get
			{
				return this._Barkod;
			}
			set
			{
				if ((this._Barkod != value))
				{
					if (this._tbl_Urunler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBarkodChanging(value);
					this.SendPropertyChanging();
					this._Barkod = value;
					this.SendPropertyChanged("Barkod");
					this.OnBarkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calisanid", DbType="Int NOT NULL")]
		public int Calisanid
		{
			get
			{
				return this._Calisanid;
			}
			set
			{
				if ((this._Calisanid != value))
				{
					if (this._tbl_Calisanlar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCalisanidChanging(value);
					this.SendPropertyChanging();
					this._Calisanid = value;
					this.SendPropertyChanged("Calisanid");
					this.OnCalisanidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Baslangic", DbType="DateTime NOT NULL")]
		public System.DateTime Baslangic
		{
			get
			{
				return this._Baslangic;
			}
			set
			{
				if ((this._Baslangic != value))
				{
					this.OnBaslangicChanging(value);
					this.SendPropertyChanging();
					this._Baslangic = value;
					this.SendPropertyChanged("Baslangic");
					this.OnBaslangicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bitis", DbType="DateTime")]
		public System.Nullable<System.DateTime> Bitis
		{
			get
			{
				return this._Bitis;
			}
			set
			{
				if ((this._Bitis != value))
				{
					this.OnBitisChanging(value);
					this.SendPropertyChanging();
					this._Bitis = value;
					this.SendPropertyChanged("Bitis");
					this.OnBitisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Calisanlar_tbl_Zimmetliler", Storage="_tbl_Calisanlar", ThisKey="Calisanid", OtherKey="cid", IsForeignKey=true)]
		public tbl_Calisanlar tbl_Calisanlar
		{
			get
			{
				return this._tbl_Calisanlar.Entity;
			}
			set
			{
				tbl_Calisanlar previousValue = this._tbl_Calisanlar.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Calisanlar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Calisanlar.Entity = null;
						previousValue.tbl_Zimmetlilers.Remove(this);
					}
					this._tbl_Calisanlar.Entity = value;
					if ((value != null))
					{
						value.tbl_Zimmetlilers.Add(this);
						this._Calisanid = value.cid;
					}
					else
					{
						this._Calisanid = default(int);
					}
					this.SendPropertyChanged("tbl_Calisanlar");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Urunler_tbl_Zimmetliler", Storage="_tbl_Urunler", ThisKey="Barkod", OtherKey="barkod", IsForeignKey=true)]
		public tbl_Urunler tbl_Urunler
		{
			get
			{
				return this._tbl_Urunler.Entity;
			}
			set
			{
				tbl_Urunler previousValue = this._tbl_Urunler.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Urunler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Urunler.Entity = null;
						previousValue.tbl_Zimmetlilers.Remove(this);
					}
					this._tbl_Urunler.Entity = value;
					if ((value != null))
					{
						value.tbl_Zimmetlilers.Add(this);
						this._Barkod = value.barkod;
					}
					else
					{
						this._Barkod = default(int);
					}
					this.SendPropertyChanged("tbl_Urunler");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Servisler")]
	public partial class tbl_Servisler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _Barkod;
		
		private int _kategoriid;
		
		private System.Nullable<int> _calisanid;
		
		private System.DateTime _serviseGelisTarihi;
		
		private System.DateTime _servisSuresi;
		
		private int _servisTutari;
		
		private bool _garantiliMi;
		
		private bool _silindi;
		
		private EntityRef<tbl_Calisanlar> _tbl_Calisanlar;
		
		private EntityRef<tbl_Urunler> _tbl_Urunler;
		
		private EntityRef<tbl_AltUrunKategori> _tbl_AltUrunKategori;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnBarkodChanging(int value);
    partial void OnBarkodChanged();
    partial void OnkategoriidChanging(int value);
    partial void OnkategoriidChanged();
    partial void OncalisanidChanging(System.Nullable<int> value);
    partial void OncalisanidChanged();
    partial void OnserviseGelisTarihiChanging(System.DateTime value);
    partial void OnserviseGelisTarihiChanged();
    partial void OnservisSuresiChanging(System.DateTime value);
    partial void OnservisSuresiChanged();
    partial void OnservisTutariChanging(int value);
    partial void OnservisTutariChanged();
    partial void OngarantiliMiChanging(bool value);
    partial void OngarantiliMiChanged();
    partial void OnsilindiChanging(bool value);
    partial void OnsilindiChanged();
    #endregion
		
		public tbl_Servisler()
		{
			this._tbl_Calisanlar = default(EntityRef<tbl_Calisanlar>);
			this._tbl_Urunler = default(EntityRef<tbl_Urunler>);
			this._tbl_AltUrunKategori = default(EntityRef<tbl_AltUrunKategori>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barkod", DbType="Int NOT NULL")]
		public int Barkod
		{
			get
			{
				return this._Barkod;
			}
			set
			{
				if ((this._Barkod != value))
				{
					if (this._tbl_Urunler.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBarkodChanging(value);
					this.SendPropertyChanging();
					this._Barkod = value;
					this.SendPropertyChanged("Barkod");
					this.OnBarkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kategoriid", DbType="Int NOT NULL")]
		public int kategoriid
		{
			get
			{
				return this._kategoriid;
			}
			set
			{
				if ((this._kategoriid != value))
				{
					if (this._tbl_AltUrunKategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkategoriidChanging(value);
					this.SendPropertyChanging();
					this._kategoriid = value;
					this.SendPropertyChanged("kategoriid");
					this.OnkategoriidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calisanid", DbType="Int")]
		public System.Nullable<int> calisanid
		{
			get
			{
				return this._calisanid;
			}
			set
			{
				if ((this._calisanid != value))
				{
					if (this._tbl_Calisanlar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncalisanidChanging(value);
					this.SendPropertyChanging();
					this._calisanid = value;
					this.SendPropertyChanged("calisanid");
					this.OncalisanidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_serviseGelisTarihi", DbType="DateTime NOT NULL")]
		public System.DateTime serviseGelisTarihi
		{
			get
			{
				return this._serviseGelisTarihi;
			}
			set
			{
				if ((this._serviseGelisTarihi != value))
				{
					this.OnserviseGelisTarihiChanging(value);
					this.SendPropertyChanging();
					this._serviseGelisTarihi = value;
					this.SendPropertyChanged("serviseGelisTarihi");
					this.OnserviseGelisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servisSuresi", DbType="DateTime NOT NULL")]
		public System.DateTime servisSuresi
		{
			get
			{
				return this._servisSuresi;
			}
			set
			{
				if ((this._servisSuresi != value))
				{
					this.OnservisSuresiChanging(value);
					this.SendPropertyChanging();
					this._servisSuresi = value;
					this.SendPropertyChanged("servisSuresi");
					this.OnservisSuresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_servisTutari", DbType="Int NOT NULL")]
		public int servisTutari
		{
			get
			{
				return this._servisTutari;
			}
			set
			{
				if ((this._servisTutari != value))
				{
					this.OnservisTutariChanging(value);
					this.SendPropertyChanging();
					this._servisTutari = value;
					this.SendPropertyChanged("servisTutari");
					this.OnservisTutariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_garantiliMi", DbType="Bit NOT NULL")]
		public bool garantiliMi
		{
			get
			{
				return this._garantiliMi;
			}
			set
			{
				if ((this._garantiliMi != value))
				{
					this.OngarantiliMiChanging(value);
					this.SendPropertyChanging();
					this._garantiliMi = value;
					this.SendPropertyChanged("garantiliMi");
					this.OngarantiliMiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_silindi", DbType="Bit NOT NULL")]
		public bool silindi
		{
			get
			{
				return this._silindi;
			}
			set
			{
				if ((this._silindi != value))
				{
					this.OnsilindiChanging(value);
					this.SendPropertyChanging();
					this._silindi = value;
					this.SendPropertyChanged("silindi");
					this.OnsilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Calisanlar_tbl_Servisler", Storage="_tbl_Calisanlar", ThisKey="calisanid", OtherKey="cid", IsForeignKey=true)]
		public tbl_Calisanlar tbl_Calisanlar
		{
			get
			{
				return this._tbl_Calisanlar.Entity;
			}
			set
			{
				tbl_Calisanlar previousValue = this._tbl_Calisanlar.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Calisanlar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Calisanlar.Entity = null;
						previousValue.tbl_Servislers.Remove(this);
					}
					this._tbl_Calisanlar.Entity = value;
					if ((value != null))
					{
						value.tbl_Servislers.Add(this);
						this._calisanid = value.cid;
					}
					else
					{
						this._calisanid = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Calisanlar");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Urunler_tbl_Servisler", Storage="_tbl_Urunler", ThisKey="Barkod", OtherKey="barkod", IsForeignKey=true)]
		public tbl_Urunler tbl_Urunler
		{
			get
			{
				return this._tbl_Urunler.Entity;
			}
			set
			{
				tbl_Urunler previousValue = this._tbl_Urunler.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Urunler.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Urunler.Entity = null;
						previousValue.tbl_Servislers.Remove(this);
					}
					this._tbl_Urunler.Entity = value;
					if ((value != null))
					{
						value.tbl_Servislers.Add(this);
						this._Barkod = value.barkod;
					}
					else
					{
						this._Barkod = default(int);
					}
					this.SendPropertyChanged("tbl_Urunler");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_AltUrunKategori_tbl_Servisler", Storage="_tbl_AltUrunKategori", ThisKey="kategoriid", OtherKey="id", IsForeignKey=true)]
		public tbl_AltUrunKategori tbl_AltUrunKategori
		{
			get
			{
				return this._tbl_AltUrunKategori.Entity;
			}
			set
			{
				tbl_AltUrunKategori previousValue = this._tbl_AltUrunKategori.Entity;
				if (((previousValue != value) 
							|| (this._tbl_AltUrunKategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_AltUrunKategori.Entity = null;
						previousValue.tbl_Servislers.Remove(this);
					}
					this._tbl_AltUrunKategori.Entity = value;
					if ((value != null))
					{
						value.tbl_Servislers.Add(this);
						this._kategoriid = value.id;
					}
					else
					{
						this._kategoriid = default(int);
					}
					this.SendPropertyChanged("tbl_AltUrunKategori");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_UrunKategori")]
	public partial class tbl_UrunKategori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Ad;
		
		private bool _Silindi;
		
		private EntitySet<tbl_Urunler> _tbl_Urunlers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    #endregion
		
		public tbl_UrunKategori()
		{
			this._tbl_Urunlers = new EntitySet<tbl_Urunler>(new Action<tbl_Urunler>(this.attach_tbl_Urunlers), new Action<tbl_Urunler>(this.detach_tbl_Urunlers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_UrunKategori_tbl_Urunler", Storage="_tbl_Urunlers", ThisKey="id", OtherKey="Kategoriid")]
		public EntitySet<tbl_Urunler> tbl_Urunlers
		{
			get
			{
				return this._tbl_Urunlers;
			}
			set
			{
				this._tbl_Urunlers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Urunlers(tbl_Urunler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_UrunKategori = this;
		}
		
		private void detach_tbl_Urunlers(tbl_Urunler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_UrunKategori = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_AltUrunKategori")]
	public partial class tbl_AltUrunKategori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Ad;
		
		private int _UrunKategoriid;
		
		private bool _Silindi;
		
		private EntitySet<tbl_Urunler> _tbl_Urunlers;
		
		private EntitySet<tbl_Servisler> _tbl_Servislers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnUrunKategoriidChanging(int value);
    partial void OnUrunKategoriidChanged();
    partial void OnSilindiChanging(bool value);
    partial void OnSilindiChanged();
    #endregion
		
		public tbl_AltUrunKategori()
		{
			this._tbl_Urunlers = new EntitySet<tbl_Urunler>(new Action<tbl_Urunler>(this.attach_tbl_Urunlers), new Action<tbl_Urunler>(this.detach_tbl_Urunlers));
			this._tbl_Servislers = new EntitySet<tbl_Servisler>(new Action<tbl_Servisler>(this.attach_tbl_Servislers), new Action<tbl_Servisler>(this.detach_tbl_Servislers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunKategoriid", DbType="Int NOT NULL")]
		public int UrunKategoriid
		{
			get
			{
				return this._UrunKategoriid;
			}
			set
			{
				if ((this._UrunKategoriid != value))
				{
					this.OnUrunKategoriidChanging(value);
					this.SendPropertyChanging();
					this._UrunKategoriid = value;
					this.SendPropertyChanged("UrunKategoriid");
					this.OnUrunKategoriidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Silindi", DbType="Bit NOT NULL")]
		public bool Silindi
		{
			get
			{
				return this._Silindi;
			}
			set
			{
				if ((this._Silindi != value))
				{
					this.OnSilindiChanging(value);
					this.SendPropertyChanging();
					this._Silindi = value;
					this.SendPropertyChanged("Silindi");
					this.OnSilindiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_AltUrunKategori_tbl_Urunler", Storage="_tbl_Urunlers", ThisKey="id", OtherKey="AltKategoriid")]
		public EntitySet<tbl_Urunler> tbl_Urunlers
		{
			get
			{
				return this._tbl_Urunlers;
			}
			set
			{
				this._tbl_Urunlers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_AltUrunKategori_tbl_Servisler", Storage="_tbl_Servislers", ThisKey="id", OtherKey="kategoriid")]
		public EntitySet<tbl_Servisler> tbl_Servislers
		{
			get
			{
				return this._tbl_Servislers;
			}
			set
			{
				this._tbl_Servislers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Urunlers(tbl_Urunler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_AltUrunKategori = this;
		}
		
		private void detach_tbl_Urunlers(tbl_Urunler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_AltUrunKategori = null;
		}
		
		private void attach_tbl_Servislers(tbl_Servisler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_AltUrunKategori = this;
		}
		
		private void detach_tbl_Servislers(tbl_Servisler entity)
		{
			this.SendPropertyChanging();
			entity.tbl_AltUrunKategori = null;
		}
	}
}
#pragma warning restore 1591
